config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments
    member do
      patch 'toggle_visibility', to: "admin#toggle_visibility", as: :un_publish
      get 'archive', to: 'posts#by_month'
    end
  end
  resources :categories, except: [:index, :show]

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :admin, only: [:index] 

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :nullify
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_one :category
	validates :title, presence: true
	validates :description, presence: true

  attr_accessor :image, :remote_image_url
  mount_uploader :image, ImageUploader

  scope :of_category, ->(category) { where(category_id: category) }

  # most simple search, need to refined
  def self.search(params)
    if params
      where('title ILIKE ? OR description ILIKE ?', "%#{params}%", "%#{params}%")
    else 
      all
    end
  end

  def self.published
    where(published: true)
  end

  def self.published_count_per_category
    published.group(:category_id).count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         #,:confirmable
  #before_create :confirmation_token
  validates :email, uniqueness: true

  # refactor: check for admin column true
  def admin?
    email == 'admin@example.com'
  end
end

private

def confirmation_token
	if self.confirm_token.blank?
	  self.confirm_token = SecureRandom.urlsafe_base64.to_s
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @posts = Post.all
    @categories = Category.all
  end

  def toggle_visibility
    post = Post.find(params[:id])
    if post.published == true
	  post.update_attributes(published: false)
	else
	  post.update_attributes(published: true)
	end
    flash[:notice] = "Post visibility has been changed for #{post.title}."
    redirect_to admin_index_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if current_user.admin?
      admin_index_path
    else
      posts_path
    end
  end

  def after_sign_out_path_for(resource)
    posts_path
  end

  def ensure_admin!
    unless current_user.admin?
      redirect_to posts_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :ensure_admin!, except: [:show]

  respond_to :html

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save!
    redirect_to admin_index_path
  end

  def update
    @category.update!(category_params)
    redirect_to admin_index_path
  end

  def destroy
    @category.destroy!
    redirect_to admin_index_path
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :ensure_admin!, only: [:destroy]

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    if @comment.save
      flash[:notice] = 'Comment successfully created'
    else
      flash[:error] = 'Comment creation failed'
    end
    redirect_to post_path(params[:post_id])
  end

  # creator and admin only
  def destroy
    if Comment.find(params[:id]).destroy
      flash[:notice] = 'Comment successfully deleted'
    else
      flash[:error] = 'Problem while deleting comment'
    end
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_id, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout false
	def index
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :by_month]
  before_action :ensure_admin!, except: [:index, :by_month, :show, :publish, :unpublish]

  def index
    @posts = all_posts_or_by_params
              .order('created_at DESC')
              .paginate(page: params[:page], per_page: 20)
    @archive = published_posts_grouped_by_month
  end

  def edit
    @post = find_post_by_id
  end

  def new
    @post = Post.new
  end

  def show
    @post = find_post_by_id
    @category = category_name_for(@post.category_id)
    @related_posts = Post.of_category(@post.category_id)
    @archive = published_posts_grouped_by_month
  end

  def create
    post = Post.new(post_params)
    if post.save
      flash[:notice] = 'Post successfully created.' 
      redirect_to admin_index_path
    else
      flash[:error] = 'Post creation failed.'
      render :new
    end
  end

  def destroy
    post = find_post_by_id
    if post.destroy
      flash[:notice] = 'Post successfully deleted.'
      redirect_to admin_index_path
    else
      flash[:error] = 'Post deletion failed.'
      redirect_to admin_index_path
    end
  end

  def update
    post = find_post_by_id
    post.update_attributes(post_params)
    if post.save
      flash[:notice] = 'Post successfully updated.' 
    else
      flash[:error] = 'Post update failed.'
    end
    redirect_to post_path(params[:id])
  end

  def category_name_for(category_id)
    return 'none' if category_id.nil?
    Category.find(category_id).name
  end

  def by_month
    @posts = Post.published
                 .where('extract(month from created_at) = ?', params[:month])
                 .paginate(page: params[:page], per_page: 3)
    @archive = published_posts_grouped_by_month
  end

  private

  def all_posts_or_by_params
    posts = if params[:category_id]
              Category.find(params[:category_id]).posts
            elsif !params[:search].nil?
              Post.search(params[:search])
            else
              Post.all
            end
    posts.published
  end

  def published_posts_grouped_by_month
    Post.published.group_by { |t| t.created_at.month }
  end

  def find_post_by_id
    Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :category_id, :published, :image, :remote_image_url)
  end
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap:       true,
      escape_html: true,
      link_attributes: { rel: 'nofollow', target: '_blank' },
    }

    extensions = {
      autolink:           true,
      superscript:        true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

def logged_in_as_admin?
  current_user && current_user.admin?
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def resolve_category_by_name(id)
    if id.nil?
      return "none"
    else
      Category.find(id).name
    end
  end

  def to_html(content)
    content.html_safe
  end
end

app/views/admin/_category.haml
%h2
  Categories
  %small= link_to '(new)', new_category_path

%table.table.table-striped.sortable{:cellspacing => "0", :width => "100%"}
  %thead
    %tr
      %th Id
      %th Name

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.id
        %td=link_to category.name, posts_path(category_id: category.id)
        %td
          = link_to "edit", edit_category_path(category)
          = link_to 'delete', category, :method => :delete, data: { confirm: "Are you sure?" }

app/views/admin/_post.haml
%h2
  Posts
  %small= link_to '(new)', new_post_path

%table.table.table-striped.sortable{:cellspacing => "0", :width => "100%"}
  %thead
    %tr
      %th Id
      %th Title
      %th Category
      %th Published

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.id
        %td= link_to post.title, post_path(post)
        %td= Category.find(post.category_id).name unless post.category_id.nil?
        %td
          = post.published
        %td
          = link_to "edit", edit_post_path(post)
          = link_to 'delete', post, :method => :delete, data: { confirm: "Are you sure?" }
          
          = link_to 'Toggle post visibility', un_publish_post_path(id: post.id), method: :patch

app/views/admin/index.haml
- if current_user  && current_user.admin?
  = render partial: 'post'
  = render partial: 'category'

app/views/categories/_form.html.haml
= form_for @category do |f|
  = f.text_field :name
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

app/views/categories/new.html.haml
%h1 New category

= render 'form'

app/views/comments/new.haml
= form_for :comment, url: post_comments_path do |f|
	= f.text_field :content
	= f.submit 

app/views/layouts/_footer.haml
- unless current_user
  = link_to 'Login', new_user_session_path

- if current_user
  = "Logged in as: #{current_user.email}"
  %br
  = link_to 'Logout', destroy_user_session_path, method: :delete

- if current_user && current_user.admin?
  %br
  = link_to 'Administration', admin_index_path

app/views/layouts/application.haml
%head
  %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
  %link{:href => "https://fonts.googleapis.com/css?family=Indie+Flower|Open+Sans:400,600i", :rel => "stylesheet"}/
  %link{:href => "https://fonts.googleapis.com/css?family=Indie+Flower|Open+Sans:400,600i", :rel => "stylesheet"}/

  = stylesheet_link_tag :application
  = javascript_include_tag :application
  = csrf_meta_tag

.logo
  = link_to posts_path do 
    .logo--main
      = "#ichundmeinblog"
    .logo--subline
      %small="Entwickeln, Bloggen, Lernen"

.flash_area
  - if flash
    = flash[:notice]
    = flash[:error]

.main-content
  = yield
  = yield(:sidebar)

.footer
  = render partial: 'layouts/footer'

app/views/layouts/sidebar/_categories.haml
- category.each do |c|
  .category
    =link_to "#{c.name} (#{category_count[c.id]})", posts_path(category_id: c.id)

app/views/layouts/sidebar/_post_archive.haml
- @posts_by_month.each do |month, posts|
  %h4 
    = link_to "#{month.strftime('%Y %B')} (#{posts.count})", posts_by_month_path(:year=> month.year, :month => month.month)

app/views/layouts/sidebar/_recent_posts.haml
%li= link_to post.title, post_path(post)

app/views/layouts/sidebar/_search_form.haml
= form_tag(posts_path, :method => "get", id: "search-form") do
  .input-group
    = text_field_tag :search, params[:search], placeholder: "Suchen", class: 'form-control'

app/views/posts/_meta.haml
%p.post--meta
  = post.created_at.strftime("%d.%b %Y")
  = " | Kommentare: #{post.comments_count}"

  - unless post.category_id.nil?
    =link_to resolve_category_by_name(post.category_id), posts_path(:category_id => post.category_id)

  %span
    = link_to "https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}" do
      = fa_icon 'facebook-official'

app/views/posts/_post_list.haml
- unless @posts.empty?
  .flexbox--wrapper
    - @posts.each do |post|
      .post-list--item
        %h1
          - if logged_in_as_admin?
            =link_to edit_post_path(post) do 
              = fa_icon "edit"
          = link_to post.title, post_path(post.id)
        

        = render partial: 'meta', locals: { post: post}

        = image_tag post.image_url(:thumb) if post.image?
        = markdown(truncate(post.description, length: 200))

        - if post.description.length > 200
          %b= link_to 'Hier weiterlesen ...', post_path(post.id)
- else
  #post
    = 'Keine Posts gefunden.'

#pagination.centered= will_paginate @posts, page_links: false

app/views/posts/_sidebar.haml
- content_for :sidebar do
  .sidebar--wrapper 
    .sidebar--item
      = render partial: 'layouts/sidebar/search_form'
    .sidebar--item 
      %h4= 'Kategorien:'
      = render partial: 'layouts/sidebar/categories', locals: { category: Category.joins(:posts).uniq.sort, category_count: Post.published_count_per_category }
    .sidebar--item
      %h4= 'Letzte Posts' 
      = render partial: 'layouts/sidebar/recent_posts', collection: Post.published.last(5), as: :post
    .sidebar--item 
      %h4= 'Archiv'
      = render partial: 'layouts/sidebar/post_archive', locals: {archive: @archive, months: (1..12).to_a }

 
          

app/views/posts/_title_and_subline.haml
%h1
  = link_to post.title, post_path(post.id)
%p.subline
  = post.created_at.strftime("%d.%b %Y")
  = " | Kommentare: #{post.comments_count}"

  - unless post.category_id.nil?
    = " | In: "
    =link_to resolve_category_by_name(post.category_id), posts_path(:category_id => post.category_id)

  %span
    = link_to "https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}" do
      = fa_icon 'facebook-official'
      = 'Teilen'

  %span
    =link_to "Editieren", edit_post_path(post) if logged_in_as_admin?

app/views/posts/by_month.haml
= render partial: 'sidebar'
= render partial: 'post_list'

app/views/posts/edit.haml
%h1="Edit Post (Id: #{@post.id})"
= form_for @post, :html => {:multipart => true} do |f|
  %br
  = f.text_field :title, size: '40'
  %br
  %br
  = f.text_area :description, size: "80x20"
  %br
  = f.label :category
  %br
  = f.select :category_id, Category.all.map{ |category| [category.name, category.id] }
  %br
  = f.file_field :image
  %br
  = f.label :remote_image_url, "or image URL"
  %br
  = f.text_field :remote_image_url
  %br
  = f.submit 
  %small=link_to 'back', posts_path

app/views/posts/index.haml
= render partial: 'sidebar'
= render partial: 'post_list'

app/views/posts/new.haml
%h1="New Post"
= form_for @post, :html => {:multipart => true} do |f|
  %br
  = f.text_field :title, size: '40'
  %br
  %br
  = f.text_area :description, size: "80x20"
  %br
  = f.label :category
  %br
  = f.select :category_id, Category.all.map{ |category| [category.name, category.id] }
  %br
  = f.file_field :image
  %br
  = f.label :remote_image_url, "or image URL"
  %br
  = f.text_field :remote_image_url
  %br
  = f.submit 
  %small=link_to 'back', posts_path

app/views/posts/show.haml
#post
  %h1
    = link_to @post.title, post_path(@post.id)
  
  %span
    = render partial: 'meta', locals: { post: @post}
    / .img-original-size= image_tag @post.image_url(:post_header)  if @post.image?

  .post--content
    = markdown(@post.description)

  .post--comments
    %b= "#{@post.comments.count} Kommentare:"

    - if @post.comments.any?
      - @post.comments.each do |c|

        .subline
          = "#{c.created_at.strftime("%Y-%m-%d")}"
          .pull-right= link_to 'delete', post_comment_path(c.post_id, c), :method => :delete, data: { confirm: "Are you sure?" } if logged_in_as_admin?

        .content
          %br= c.content

  .form-group
    = form_for :comment, url: post_comments_path(post_id: @post.id), action: :new do |f|
      = f.text_area :content, rows: 4, cols: 40, placeholder: 'Schreib einen Kommentar', class: 'form-control', id: 'comment'
      %br= f.submit :Absenden, class: 'btn btn-default pull-right'

  / .related-items
  /   %h6= 'Ähnliche Beiträge'
  /   %ul
  /     - @related_posts.each do |post|  
  /       %li= link_to post.title